//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssds
{
    using System;
    using System.Collections.Generic;
    
    public partial class notlarr
    {
        public short NotID { get; set; }
        public short Not1 { get; set; }
        public short Not2 { get; set; }
    }
}
