//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _111
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public string OgrenciNumara { get; set; }
        public string OgrenciAdSoyad { get; set; }
        public string OgrenciBolum { get; set; }
        public string OgrenciFakulte { get; set; }
    }
}
