//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _111
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class odev3Entities : DbContext
    {
        public odev3Entities()
            : base("name=odev3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
    
        public virtual int proc_sil(string ogrencinumara)
        {
            var ogrencinumaraParameter = ogrencinumara != null ?
                new ObjectParameter("ogrencinumara", ogrencinumara) :
                new ObjectParameter("ogrencinumara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_sil", ogrencinumaraParameter);
        }
    
        public virtual int sp_guncelle(string ogrencinumara, string ogrenciadsoyad, string ogrencibolum, string ogrencifakulte)
        {
            var ogrencinumaraParameter = ogrencinumara != null ?
                new ObjectParameter("ogrencinumara", ogrencinumara) :
                new ObjectParameter("ogrencinumara", typeof(string));
    
            var ogrenciadsoyadParameter = ogrenciadsoyad != null ?
                new ObjectParameter("ogrenciadsoyad", ogrenciadsoyad) :
                new ObjectParameter("ogrenciadsoyad", typeof(string));
    
            var ogrencibolumParameter = ogrencibolum != null ?
                new ObjectParameter("ogrencibolum", ogrencibolum) :
                new ObjectParameter("ogrencibolum", typeof(string));
    
            var ogrencifakulteParameter = ogrencifakulte != null ?
                new ObjectParameter("ogrencifakulte", ogrencifakulte) :
                new ObjectParameter("ogrencifakulte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guncelle", ogrencinumaraParameter, ogrenciadsoyadParameter, ogrencibolumParameter, ogrencifakulteParameter);
        }
    
        public virtual int sp_Ogrenci_Kaydet(string ogrenciNumara, string ogrenciadsoyad, string ogrencibolum, string ogrencifakulte)
        {
            var ogrenciNumaraParameter = ogrenciNumara != null ?
                new ObjectParameter("ogrenciNumara", ogrenciNumara) :
                new ObjectParameter("ogrenciNumara", typeof(string));
    
            var ogrenciadsoyadParameter = ogrenciadsoyad != null ?
                new ObjectParameter("ogrenciadsoyad", ogrenciadsoyad) :
                new ObjectParameter("ogrenciadsoyad", typeof(string));
    
            var ogrencibolumParameter = ogrencibolum != null ?
                new ObjectParameter("ogrencibolum", ogrencibolum) :
                new ObjectParameter("ogrencibolum", typeof(string));
    
            var ogrencifakulteParameter = ogrencifakulte != null ?
                new ObjectParameter("ogrencifakulte", ogrencifakulte) :
                new ObjectParameter("ogrencifakulte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Ogrenci_Kaydet", ogrenciNumaraParameter, ogrenciadsoyadParameter, ogrencibolumParameter, ogrencifakulteParameter);
        }
    
        public virtual ObjectResult<sp_Ogrenci_Listele_Result> sp_Ogrenci_Listele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Ogrenci_Listele_Result>("sp_Ogrenci_Listele");
        }
    }
}
