#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq_odev3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="odev3")]
	public partial class odev3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOgrenci(Ogrenci instance);
    partial void UpdateOgrenci(Ogrenci instance);
    partial void DeleteOgrenci(Ogrenci instance);
    #endregion
		
		public odev3DataContext() : 
				base(global::linq_odev3.Properties.Settings.Default.odev3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public odev3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public odev3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public odev3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public odev3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ogrenci> Ogrencis
		{
			get
			{
				return this.GetTable<Ogrenci>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenci")]
	public partial class Ogrenci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OgrenciNumara;
		
		private string _OgrenciAdSoyad;
		
		private string _OgrenciBolum;
		
		private string _OgrenciFakulte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOgrenciNumaraChanging(string value);
    partial void OnOgrenciNumaraChanged();
    partial void OnOgrenciAdSoyadChanging(string value);
    partial void OnOgrenciAdSoyadChanged();
    partial void OnOgrenciBolumChanging(string value);
    partial void OnOgrenciBolumChanged();
    partial void OnOgrenciFakulteChanging(string value);
    partial void OnOgrenciFakulteChanged();
    #endregion
		
		public Ogrenci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciNumara", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OgrenciNumara
		{
			get
			{
				return this._OgrenciNumara;
			}
			set
			{
				if ((this._OgrenciNumara != value))
				{
					this.OnOgrenciNumaraChanging(value);
					this.SendPropertyChanging();
					this._OgrenciNumara = value;
					this.SendPropertyChanged("OgrenciNumara");
					this.OnOgrenciNumaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciAdSoyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OgrenciAdSoyad
		{
			get
			{
				return this._OgrenciAdSoyad;
			}
			set
			{
				if ((this._OgrenciAdSoyad != value))
				{
					this.OnOgrenciAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._OgrenciAdSoyad = value;
					this.SendPropertyChanged("OgrenciAdSoyad");
					this.OnOgrenciAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciBolum", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OgrenciBolum
		{
			get
			{
				return this._OgrenciBolum;
			}
			set
			{
				if ((this._OgrenciBolum != value))
				{
					this.OnOgrenciBolumChanging(value);
					this.SendPropertyChanging();
					this._OgrenciBolum = value;
					this.SendPropertyChanged("OgrenciBolum");
					this.OnOgrenciBolumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciFakulte", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OgrenciFakulte
		{
			get
			{
				return this._OgrenciFakulte;
			}
			set
			{
				if ((this._OgrenciFakulte != value))
				{
					this.OnOgrenciFakulteChanging(value);
					this.SendPropertyChanging();
					this._OgrenciFakulte = value;
					this.SendPropertyChanged("OgrenciFakulte");
					this.OnOgrenciFakulteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
