--create proc sp_Ogrenci_Kaydet
--(
--@ogrenciNumara nvarchar(10),
--@ogrenciadsoyad nvarchar(50),
--@ogrencibolum nvarchar(50),
--@ogrencifakulte nvarchar(50)
--)
--as
--begin
--insert into Ogrenci (OgrenciNumara,OgrenciAdSoyad,OgrenciBolum,OgrenciFakulte)
--values(@ogrenciNumara,@ogrenciadsoyad,@ogrencibolum,@ogrencifakulte)
--end
