//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmID { get; set; }
        public string FilmAdi { get; set; }
        public string FilmKisaBilgi { get; set; }
        public string FilmFragmanLink { get; set; }
    }
}
