//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTİTY_FRAMEWORK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayin
    {
        public int YayinID { get; set; }
        public int FilmID { get; set; }
        public int SalonID { get; set; }
        public System.DateTime FYZaman { get; set; }
    }
}
